version: '3.4'

services:
  movies:
    build:
      context: ..
      dockerfile: movies/Dockerfile_dev
    ports:
      - "8080:80"
  movies_tests:
    build:
      context: ..
      dockerfile: movies/Dockerfile_test