FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY /movies/requirements/dev.txt /code/requirements/
RUN pip install -r requirements/dev.txt
COPY /movies/ /code/
EXPOSE 80
CMD ["python", "manage.py", "test", "movies_list"]